# Generated by Django 4.1.5 on 2023-01-30 11:27

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default=None, upload_to='uploads', verbose_name='Картинка'),
        ),
    ]
