# Generated by Django 4.1.5 on 2023-01-30 11:28

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='NULL', upload_to='uploads', verbose_name='Картинка'),
        ),
    ]
